name: Run Optimization

on:
  workflow_dispatch:
    inputs:
      num_stocks:
        description: 'Number of stocks'
        required: true
        type: integer
      stock_symbols:
        description: 'Comma-separated stock symbols'
        required: true
        type: string

jobs:
  run-optimization:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run optimization script
      run: |
        python Optimization_Logic.py ${{ github.event.inputs.num_stocks }} "${{ github.event.inputs.stock_symbols }}"

    - name: Upload results artifact
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: results.json
